name: "create pr to sync develop with master"

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed

jobs:
  create-sync-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set Timestamp
        env:
          TZ: 'Asia/Tokyo'
        run: echo "TIMESTAMP=$(date '+%Y%m%d%H%M%S')" > $GITHUB_ENV

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_BRANCH_INTO: 'develop'
          MERGE_BRANCH_FROM: 'release/merged_master_${{ env.TIMESTAMP }}'
          PR_TITLE: |
            '${{ github.repositoryUrl }}/pull/${{ github.event.pull_request.number }}'
            'This PR(created by ${{ github.run_id }}) syncs the develop branch with the latest changes from master.'
        run: |
          git checkout -b $MERGE_BRANCH_FROM
          git push origin $MERGE_BRANCH_FROM
          gh pr create --draft --base $MERGE_BRANCH_INTO --head $MERGE_BRANCH_FROM --title "$PR_TITLE" --body "$PR_BODY"
